# Generated by Django 5.2.4 on 2025-07-09 18:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='uid',
            field=models.CharField(auto_created=True, default=uuid.uuid4, max_length=255, primary_key=True, serialize=False, unique=True),
        ),
    ]
