# Generated by Django 5.0.1 on 2024-02-25 04:22

import tools.generate_unique_ids
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="listeningsession",
            name="session_id",
            field=models.CharField(
                default=tools.generate_unique_ids.UniqueIdGenerator.generate_listening_session_id,
                max_length=132,
            ),
        ),
    ]
