# Generated by Django 5.0.1 on 2024-02-28 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("music", "0002_listeningsession_session_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="listeningsession",
            old_name="song_id",
            new_name="current_song_id",
        ),
        migrations.AddField(
            model_name="listeningsession",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterUniqueTogether(
            name="listeningsession",
            unique_together={("creator", "is_active")},
        ),
    ]
