# Generated by Django 5.2.4 on 2025-07-09 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomErrors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=122)),
                ('status_code', models.IntegerField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('count', models.PositiveIntegerField()),
            ],
        ),
    ]
